# Generated by Django 6.0.1 on 2026-01-14 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_make_email_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('total_submissions', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('beginner_solved', models.IntegerField(default=0)),
                ('beginner_avg_score', models.FloatField(default=0.0)),
                ('beginner_attempts', models.IntegerField(default=0)),
                ('intermediate_solved', models.IntegerField(default=0)),
                ('intermediate_avg_score', models.FloatField(default=0.0)),
                ('intermediate_attempts', models.IntegerField(default=0)),
                ('advanced_solved', models.IntegerField(default=0)),
                ('advanced_avg_score', models.FloatField(default=0.0)),
                ('advanced_attempts', models.IntegerField(default=0)),
                ('category_stats', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User stats',
            },
        ),
    ]
