# Generated by Django 6.0.1 on 2026-01-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userstats'),
    ]

    operations = [
    ]
