# Generated by Django 6.0.1 on 2026-01-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_creditbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditbalance',
            name='total_credits_used',
        ),
        migrations.AddField(
            model_name='creditbalance',
            name='max_credits',
            field=models.IntegerField(default=10),
        ),
    ]
