# Generated by Django 6.0.1 on 2026-01-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_creditbalance_total_credits_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditbalance',
            name='credits_remaining',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='creditbalance',
            name='max_credits',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token_type',
            field=models.CharField(choices=[('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('magic_verification', 'Magic Verification')], db_index=True, max_length=20),
        ),
    ]
