# Generated by Django 6.0.1 on 2026-01-21 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_creditbalance_credits_remaining_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNodeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, default='custom', max_length=100)),
                ('icon_name', models.CharField(default='Box', max_length=50)),
                ('description', models.TextField()),
                ('tooltip', models.TextField(blank=True)),
                ('properties', models.JSONField(default=list)),
                ('inputs', models.IntegerField(default=1)),
                ('outputs', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Node Definition',
                'verbose_name_plural': 'Custom Node Definitions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'type')},
            },
        ),
    ]
