# Generated by Django 6.0.1 on 2026-01-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customnodedefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='component_usage',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userstats',
            name='dimension_completeness_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='dimension_cost_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='dimension_performance_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='dimension_reliability_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='dimension_scalability_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='dimension_security_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='improvement_summary',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userstats',
            name='score_trends',
            field=models.JSONField(default=list),
        ),
    ]
