# Generated by Django 6.0.1 on 2026-01-25 04:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userprofile_onboarding_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldenGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('graph_json', models.JSONField()),
                ('graph_hash', models.CharField(max_length=64, unique=True)),
                ('expected_answer', models.TextField()),
                ('baseline_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Golden Graph',
                'verbose_name_plural': 'Golden Graphs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('call_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('endpoint_name', models.CharField(db_index=True, max_length=100)),
                ('graph_json', models.JSONField()),
                ('graph_hash', models.CharField(db_index=True, max_length=64)),
                ('graph_schema_version', models.CharField(default='1.0', max_length=20)),
                ('system_prompt_version', models.CharField(db_index=True, default='1.0', max_length=20)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('model_parameters', models.JSONField(default=dict)),
                ('response_text', models.TextField(blank=True)),
                ('token_usage', models.JSONField(default=dict)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('finish_reason', models.CharField(blank=True, max_length=50)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'LLM Call Log',
                'verbose_name_plural': 'LLM Call Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'timestamp'], name='api_llmcall_model_n_b0ec7c_idx'), models.Index(fields=['system_prompt_version', 'timestamp'], name='api_llmcall_system__df1eac_idx')],
            },
        ),
        migrations.CreateModel(
            name='JudgeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('graph_fidelity_score', models.IntegerField()),
                ('logical_correctness_score', models.IntegerField()),
                ('instruction_adherence_score', models.IntegerField()),
                ('hallucination_flag', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('judge_model', models.CharField(default='gemini-2.0-flash', max_length=100)),
                ('evaluation_latency_ms', models.IntegerField(blank=True, null=True)),
                ('llm_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='api.llmcalllog')),
            ],
            options={
                'verbose_name': 'Judge Evaluation',
                'verbose_name_plural': 'Judge Evaluations',
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
