# Generated by Django 6.0.1 on 2026-01-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_llm_observability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeevaluation',
            name='judge_model',
            field=models.CharField(default='gemini-3-flash-preview', max_length=100),
        ),
    ]
