# Generated by Django 6.0.1 on 2026-01-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_judgeevaluation_judge_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='problems_attempted',
            field=models.IntegerField(default=0),
        ),
    ]
